## Dense Layer

In [1]:
from tensorflow.keras.models import Sequential

In [2]:
from tensorflow.keras.layers import Dense, Activation

In [3]:
# instance of Sequetial 
model = Sequential()

In [4]:
# model with 1 dense layer having 8 neurons/units
layer = Dense(units = 8, input_shape = (4,) , activation = 'relu')
model.add(layer)

In [5]:
# display weight matrix
layer.get_weights() 

[array([[ 0.4232784 , -0.3686991 , -0.04080641, -0.12326401,  0.06683493,
          0.5541516 , -0.4060478 ,  0.43981892],
        [ 0.23578298,  0.5128315 , -0.4366511 , -0.06179553,  0.09152663,
          0.110668  , -0.1560691 , -0.07480967],
        [-0.62733155,  0.34627205,  0.36199445,  0.631175  , -0.25977463,
         -0.21799394,  0.18956554,  0.10730809],
        [-0.26339066, -0.22317716, -0.08162546, -0.49736738, -0.67495465,
         -0.6323882 , -0.02098018, -0.05178785]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [6]:
print('Input Shape of layer : '+ str(layer.input_shape))

Input Shape of layer : (None, 4)


In [7]:
print('Output Shape of layer : '+ str(layer.output_shape))

Output Shape of layer : (None, 8)


### Calculation of Output shape of layer
Input shape = (*,4)

Weight/kernel matrix shape = (4,8)

dot(input,kernel) =  ( * ,4) * (4,8) = ( * ,8)

In [8]:
# summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


## Convolution layer

In [9]:
import tensorflow as tf

In [10]:
# conv2D layer 

# 5x5 RGB pixel image with batch size=4
input_shape = (4, 5, 5, 3)
x = tf.random.normal(input_shape)
y1 = tf.keras.layers.Conv2D(2, kernel_size= 3, activation='relu')(x)
print('Shape after convolution '+ str(y1.shape))

# (5 x 5) * (3 x 3) = (5-3+1)x(5-3+1) = (3 x 3)

Shape after convolution (4, 3, 3, 2)


<img src="https://miro.medium.com/max/494/1*1VJDP6qDY9-ExTuQVEOlVg.gif"></img>

## CNN model

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, Flatten, BatchNormalization, MaxPooling2D

In [12]:
model1 =  Sequential()
model1.add(Conv2D(64, kernel_size=3, activation='relu',input_shape=(28,28,1)))
model1.add(BatchNormalization()) 
model1.add(Conv2D(32, kernel_size=3, activation='relu'))
model1.add(BatchNormalization()) 
model1.add(MaxPooling2D(2))

model1.add(Dropout(rate=0.25))

# converts the pooled feature map to a single column that is passed to the fully connected layer
model1.add(Flatten())

#hidden dense(fully connected) layer
model1.add(Dense(256,activation='relu'))

# output layer
model1.add(Dense(62,activation='softmax'))
# here 62 is no of output classes (it may vary according to no of output classes)
# softmax activation varies output between 0-1

In [13]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 64)        640       
_________________________________________________________________
batch_normalization (BatchNo (None, 26, 26, 64)        256       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 32)        18464     
_________________________________________________________________
batch_normalization_1 (Batch (None, 24, 24, 32)        128       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 4608)             

## Embedded Layer

In [14]:
import tensorflow as tf
import numpy as np

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [16]:
model = tf.keras.Sequential()

# Input integer matrix shape = (batch, input_length)
# Here, vocab_size=100. So, input matrix should not have word index ie.integer encoded value greater than 99
model.add(tf.keras.layers.Embedding(100, 8, input_length=4))

#compile the model
model.compile(optimizer='rmsprop', loss='mse')


In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              800       
Total params: 800
Trainable params: 800
Non-trainable params: 0
_________________________________________________________________


In [18]:
# Here, batch=10, input_length=4
input_array = np.random.randint(100, size=(10, 4))
output_array = model.predict(input_array)
print('Input shape of Layer:'+str(input_array.shape))
print('Output shape of Layer:'+str(output_array.shape))

Input shape of Layer:(10, 4)
Output shape of Layer:(10, 4, 8)


Input shape: (batch_size, input_length).

Output shape: (batch_size, input_length, output_dim).


## LSTM Layer

In [19]:
inputs = tf.random.normal([32, 10, 8])
lstm = tf.keras.layers.LSTM(units=4)
output = lstm(inputs)
print('Output Shape: '+ str(output.shape))

Output Shape: (32, 4)


In [20]:
lstm = tf.keras.layers.LSTM(units=4, return_sequences=True, return_state=True)
# return_sequences=True returns last output in output sequence or full sequence
# return_state=True returns last state in addition to output

whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
print(whole_seq_output.shape)
print(final_memory_state.shape)
print(final_carry_state.shape)

(32, 10, 4)
(32, 4)
(32, 4)


## Custom Block

In [21]:
# define and initalize X of shape (2,20)
X = tf.random.uniform(shape=(2, 20))
X

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[0.8620826 , 0.75025415, 0.02533031, 0.14355016, 0.3470168 ,
        0.02370191, 0.7971227 , 0.8908745 , 0.8679559 , 0.07242513,
        0.503598  , 0.32010305, 0.34981775, 0.9261557 , 0.68355024,
        0.14114451, 0.9786632 , 0.8890028 , 0.23500371, 0.9707663 ],
       [0.41347814, 0.5919939 , 0.30091405, 0.05587864, 0.5842637 ,
        0.81562054, 0.48869157, 0.39086843, 0.1710186 , 0.63337743,
        0.1183573 , 0.78289664, 0.03036654, 0.7057227 , 0.89814925,
        0.49736297, 0.1929071 , 0.05557454, 0.832667  , 0.0826602 ]],
      dtype=float32)>

In [22]:
class MLP(tf.keras.Model):
    def __init__(self):
        # Call the constructor of the 'MLP' parent class 'Block' to perform the required initialization. 
        super().__init__()
       
        # instantiating 2 fully connected layers
        self.hidden = tf.keras.layers.Dense(units=256, activation='relu')   # Hidden layer
        self.out = tf.keras.layers.Dense(units=10)  # Output layer

    # Define the forward propagation of the model ie. how to return the required model output based on the input `X`
    def call(self, X):
        return self.out(self.hidden((X)))

In [23]:
net = MLP()
net.call(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.24756399, -0.05796289, -0.22194023, -0.41325736,  0.32460323,
         0.27138254, -0.12445317,  0.06097393,  0.2741508 , -0.06754197],
       [-0.4326312 , -0.18918397,  0.05436459, -0.07648823, -0.00182199,
         0.00101668,  0.02840006, -0.12969065,  0.18816873,  0.10812622]],
      dtype=float32)>

## Sequential Block

In [24]:
# define and initalize X of shape (2,20)
X = tf.random.uniform(shape=(2, 20))
X

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[0.81053364, 0.550128  , 0.9774598 , 0.7618586 , 0.97323024,
        0.6329963 , 0.90631986, 0.8550713 , 0.6298326 , 0.208588  ,
        0.25095522, 0.61522675, 0.41562796, 0.22926211, 0.8895987 ,
        0.4417627 , 0.3018099 , 0.00286567, 0.37771118, 0.522321  ],
       [0.6203269 , 0.11218929, 0.07014143, 0.48871315, 0.6522603 ,
        0.8096292 , 0.8404658 , 0.7782121 , 0.92440355, 0.18524182,
        0.22505367, 0.07472241, 0.8036076 , 0.11100793, 0.47373438,
        0.18343496, 0.9961076 , 0.1512729 , 0.00883961, 0.3072629 ]],
      dtype=float32)>

In [25]:
# implementing our own sequential class to understand working of sequential block
class MySequential(tf.keras.Model):
    def __init__(self, *args):
        
        # Call the constructor of the 'MySequential' parent class 'Block' to perform the required initialization.
        super().__init__()
        
        self.modules = []
        for block in args:
            # 'block' is an instance of a 'tf.keras.layers.Layer' subclass
            self.modules.append(block)

    def call(self, X):
        for module in self.modules:
            X = module(X)
        return X

In [26]:
net = MySequential(
        tf.keras.layers.Dense(units=256, activation='relu'),
        tf.keras.layers.Dense(10))
net.call(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.12157557,  0.33672288,  0.12058124,  0.0449957 , -0.05865243,
         0.06890902,  0.21493694, -0.00678845, -0.2616074 ,  0.22603808],
       [ 0.08626123,  0.04644654,  0.06064051,  0.14138924, -0.10414955,
         0.16660346,  0.20093785,  0.05329151, -0.17403625,  0.13958772]],
      dtype=float32)>