# Gradient Descent

In [1]:
import numpy as np
import pandas as pd

In [2]:
# training values
x = np.array([[3,8,10],
             [10,7,2],
             [2,9,15],
             [1,12,34],
             [3,1,9]])
y = [[51],[60],[57],[85],[22]]

In [3]:
def random_weights(x):
    return (np.random.rand(x.shape[1],1)*2)-1
w = random_weights(x) # here the values of bias is taken as zero(0)
print(w)

[[ 0.82625891]
 [ 0.9287979 ]
 [-0.08701681]]


In [4]:
# learning rate
lr = 0.0001

In [5]:
# no of epoches
n_epoch=10000

In [6]:
# here lr = learning rate , n_epoch = number of time the process repeate
def simple_gradient_descent(x,y,w,lr,n_epoch):
    cost_list = []  # initialize list to store epochs and cost
    
    y_hat = np.dot(x,w)  # calculate y_hat for first iteration
    
    for epoch in range(n_epoch):  
        
        dcostdw = 2*0.5*np.dot(-x.T,(y-y_hat))   # notice change from previous function "nn_batch". 
                                                #  Matrix multiplication dcostdw (3x1) = tranpose(X) (3x4)  * (y - y_hat) (4x1) 
                                                # above matrix shapes correspond to below example. for other example shapes may change but this function will work withput any changes needed.
        
        w = w - lr*dcostdw  # w new (3x1) = w (3x1) - dcostdw (3x1)
        y_hat = np.dot(x,w) # calculate new y_hat using new weights after above steps
        cost = 0.5*np.sum((y - y_hat)**2)  # calculate new cost
        cost_list.append([epoch,cost])
        # printing of epoches
        if epoch%1000==0:
            print("epoch :{:d} cost:{:f}".format(epoch,cost))
        if cost <= 0.001:  # if the cost is less then 0.001 then we will stop the loop
            print("epoch :{:d} cost:{:f}".format(epoch,cost))
            break

    cost_list = pd.DataFrame(cost_list,columns=['epoch','cost'])
    return w,cost_list

In [7]:
w,cost_list = simple_gradient_descent(x,y,w,lr,n_epoch)
print("y_hat_final:\n",np.dot(x,w))
print("trained weights :\n",w)

epoch :0 cost:4275.357333
epoch :1000 cost:0.153760
epoch :2000 cost:0.003712
epoch :2353 cost:0.000997
y_hat_final:
 [[50.98183954]
 [60.0091316 ]
 [56.98187193]
 [85.00505976]
 [22.03502771]]
trained weights :
 [[3.00595233]
 [3.99200219]
 [1.0027965 ]]


Thank you

<p><a href="5.Backpropagation-and-Optimization.md">Next>></a></p>